name: Update Dependencies
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 8 * * *"
    - cron: "0 14 * * *"
    - cron: "0 20 * * *"
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: false
          submodules: true
          clean: false
          fetch-depth: 0
          #persist-credentials: false
      - name: "Import bot's GPG key for signing commits"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.ACTION_COMMIT_SING_PRIVATE_KEY }}
          passphrase: ${{ secrets.ACTION_COMMIT_SING_PASS }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Extract commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update submodules
        id: mod
        run: |
          git config --global user.name "Madman10K"
          git config --global user.email "contact@madladsquad.com"
          git fetch --all
          git checkout auto || git checkout -b auto
          o=$(git submodule update --remote --merge)
          echo "out=${o:0:1}?" >> $GITHUB_OUTPUT
      - name: Commit
        if: "steps.mod.outputs.out != '?'"
        id: commit
        run: |
          (git add . && git commit -m "auto" && git push origin auto && echo "com=+" >> $GITHUB_OUTPUT) || echo "com=?" >> $GITHUB_OUTPUT
      - name: Test
        run: "echo '${{ steps.mod.outputs.out }} ${{ steps.commits.outputs.com }}!'"
      - name: Create PR
        if: "steps.mod.outputs.out != '?' && steps.commit.outputs.com != '?'"
        uses: JasonEtco/create-an-issue@v2 
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_ISSUE_SECRET }}
        with:
          filename: .github/auto-issue-template.md
          update_existing: true
          search_existing: open
